#!/bin/sh
set -e

# Se crean las bases de datos independientes
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
  CREATE DATABASE condodb;
  GRANT ALL PRIVILEGES ON DATABASE condodb TO $POSTGRES_USER;

  CREATE DATABASE paymentdb;
  GRANT ALL PRIVILEGES ON DATABASE paymentdb TO $POSTGRES_USER;

  CREATE DATABASE expensedb;
  GRANT ALL PRIVILEGES ON DATABASE expensedb TO $POSTGRES_USER;

  CREATE DATABASE billingdb;
  GRANT ALL PRIVILEGES ON DATABASE billingdb TO $POSTGRES_USER;

  CREATE DATABASE keycloak;
  GRANT ALL PRIVILEGES ON DATABASE keycloak TO $POSTGRES_USER;
EOSQL