server:
  port: 8081
  servlet:
    session:
      timeout: 30m

spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:8081