server:
  port: 8222

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: condo
          uri: lb://CONDO-SERVICE
          predicates:
            - Path=/residents,/residents/**,/apartments,/apartments/**
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments,/payments/**
        - id: expense
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expenses,/expenses/**
        - id: billing
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing,/billing/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/condoflow
          jwk-set-uri: http://keycloak:8080/realms/condoflow/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info