server:
  port: 8222
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://auth-service/oauth2/default
          jwk-set-uri: http://auth-service/.well-known/jwks.json
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**