management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,refresh
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
server:
  port: 8222
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://auth-service/oauth2/default
          jwk-set-uri: http://auth-service/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users,/users/**
#              filters:
#                - TokenRelay
            - id: auth
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**